/*
MIT License

Copyright (c) 2018 Yuanmeng Zhao (SharkRetriever)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
 */
package me.rayzz.uwataloner.generatedapiobjects

import me.rayzz.uwataloner.apiobjects.Subject

/**
 * Stores a list of all known subjects, stored in Subject objects
 */
object SubjectsList {
    // GET /codes/subjects.{format}
    fun getSubjectsList(): List<Subject> {
        return listOf(
                Subject("AADMS", "Arts Administration Specialization Seminar"),
                Subject("AADMS", "Arts Administration Specialization Seminar"),
                Subject("AB", "Arabic (WLU)"),
                Subject("ACC", "Accounting"),
                Subject("ACINTY", "Academic Integrity"),
                Subject("ACTSC", "Actuarial Science"),
                Subject("ADMGT", "Advanced Management"),
                Subject("AES", "Applied Environmental Studies"),
                Subject("AFM", "Accounting and Financial Managment"),
                Subject("AHS", "Applied Health Sciences"),
                Subject("AMATH", "Applied Mathematics"),
                Subject("ANTH", "Anthropology"),
                Subject("APHYS", "Applied Physics"),
                Subject("APPLS", "Applied Language Studies"),
                Subject("ARBUS", "Arts and Business"),
                Subject("ARCH", "Architecture"),
                Subject("ARCHL", "Archeology (WLU)"),
                Subject("ART", "Art"),
                Subject("ARTS", "Arts"),
                Subject("ASIAN", "Asian Studies"),
                Subject("ASTRN", "Astronomy (WLU)"),
                Subject("AVIA", "Aviation"),
                Subject("BASE", "Bridge to Academic Success in English"),
                Subject("BE", "Business Entrepreneurship"),
                Subject("BET", "Business, Entrepreneurship and Technology"),
                Subject("BIOL", "Biology"),
                Subject("BME", "Biomedical Engineering"),
                Subject("BOT", "Botany (WLU)"),
                Subject("BUS", "Business"),
                Subject("CCIV", "Classical Civilization"),
                Subject("CDNST", "Canadian Studies"),
                Subject("CEDEV", "Children's Education & Development (WLU)"),
                Subject("CHE", "Chemical Engineering"),
                Subject("CHEM", "Chemistry"),
                Subject("CHINA", "Chinese"),
                Subject("CIVE", "Civil Engineering"),
                Subject("CLAS", "Classical Studies"),
                Subject("CM", "Computational Mathematics"),
                Subject("CMW", "Church Music and Worship"),
                Subject("CO", "Combinatorics and Optimization"),
                Subject("COGSCI", "Cognitive Science"),
                Subject("COMM", "Commerce"),
                Subject("COMPT", "Computing (WLU)"),
                Subject("COMST", "Communication Studies (WLU)"),
                Subject("CONST", "Contemporary Studies (WLU)"),
                Subject("COOP", "Co-op"),
                Subject("CROAT", "Croatian"),
                Subject("CS", "Computer Science"),
                Subject("CT", "Catholic Thought"),
                Subject("CULMG", "Cultural Management"),
                Subject("CULT", "Cultural Studies"),
                Subject("DAC", "Digital Arts Communication"),
                Subject("DANCE", "Dance"),
                Subject("DEI", "Digital Experience Innovation"),
                Subject("DES", "Design"),
                Subject("DEVIS", "Development & International Studies (WLU)"),
                Subject("DM", "Design and Manufacturing"),
                Subject("DRAMA", "Drama"),
                Subject("DUTCH", "Dutch"),
                Subject("EARTH", "Earth Science"),
                Subject("EASIA", "East Asian Studies"),
                Subject("EBUS", "Environment and Business"),
                Subject("ECE", "Electrical and Computer Engineering"),
                Subject("ECON", "Economics"),
                Subject("EFAS", "English for Academic Success"),
                Subject("ELE", "Electrical Engineering"),
                Subject("ELPE", "English Language Proficiency Examination"),
                Subject("EMLS", "English for Multilingual Speakers"),
                Subject("ENBUS", "Environment and Business"),
                Subject("ENGL", "English"),
                Subject("ENVE", "Environmental Engineering"),
                Subject("ENVS", "Environmental Studies"),
                Subject("ERS", "Environment and Resource Studies"),
                Subject("ESL", "English as a Second Language"),
                Subject("EVSY", "Environment and Society"),
                Subject("FILM", "Film (WLU)"),
                Subject("FINAN", "Finance"),
                Subject("FINE", "Fine Arts"),
                Subject("FR", "French Studies"),
                Subject("FRCS", "French Cultural Studies"),
                Subject("GBDA", "Global Business and Digital Arts"),
                Subject("GEMCC", "Geography and Environmental Mgmt, Climate Change"),
                Subject("GENE", "General Engineering"),
                Subject("GEOE", "Geological Engineering"),
                Subject("GEOG", "Geography"),
                Subject("GEOL", "Geology (WLU)"),
                Subject("GER", "German"),
                Subject("GERON", "Gerontology"),
                Subject("GGOV", "Global Governance"),
                Subject("GLOBAL", "Global Studies (WLU)"),
                Subject("GRAD", "Continuing Graduate Studies"),
                Subject("GRK", "Greek"),
                Subject("GS", "Graduate Studies"),
                Subject("HEBRW", "Hebrew (WLU)"),
                Subject("HIST", "History"),
                Subject("HLTH", "Health Studies"),
                Subject("HRCS", "Human Relations & Counselling Studies"),
                Subject("HRM", "Human Resources Management"),
                Subject("HS", "High School"),
                Subject("HSG", "Health Studies and Gerontology"),
                Subject("HUMSC", "Human Sciences"),
                Subject("HUNGN", "Hungarian"),
                Subject("IFS", "Inter-Faculty Studies"),
                Subject("INDEV", "International Development"),
                Subject("INTEG", "Integrated Studies"),
                Subject("INTERN", "Internship"),
                Subject("INTST", "International Studies"),
                Subject("INTTS", "International Trade Seminars"),
                Subject("IS", "Independent Studies"),
                Subject("ISS", "Interdisciplinary Social Sciences"),
                Subject("ITAL", "Italian"),
                Subject("ITALST", "Italian Studies"),
                Subject("JAPAN", "Japanese"),
                Subject("JS", "Jewish Studies"),
                Subject("KIN", "Kinesiology"),
                Subject("KOREA", "Korean"),
                Subject("KPE", "Kinesiology and Physical Education (WLU)"),
                Subject("LANG", "Language (WLU)"),
                Subject("LAT", "Latin"),
                Subject("LATAM", "Latin American Studies"),
                Subject("LED", "Local Economic Development"),
                Subject("LS", "Legal Studies"),
                Subject("LSC", "Legal Studies and Criminology"),
                Subject("MATBUS", "Mathematical Business"),
                Subject("MATH", "Mathematics"),
                Subject("ME", "Mechanical Engineering"),
                Subject("MEDST", "Media Studies (WLU)"),
                Subject("MEDVL", "Medieval Studies"),
                Subject("MENV", "Man Environment"),
                Subject("MES", "Middle Eastern Studies"),
                Subject("MI", "Mediterranean Studies (WLU)"),
                Subject("MISC", "Miscellaneous"),
                Subject("MNS", "Materials and Nano-Sciences"),
                Subject("MSCI", "Management Sciences"),
                Subject("MSE", "Management & Systems"),
                Subject("MTE", "Mechatronics Engineering"),
                Subject("MTHEL", "Mathematics Elective"),
                Subject("MUSIC", "Music"),
                Subject("NANO", "Nanotechnology"),
                Subject("NATST", "Native Studies"),
                Subject("NE", "Nanotechnology Engineering"),
                Subject("NES", "Near Eastern Studies (WLU)"),
                Subject("OPTOM", "Optometry"),
                Subject("PACS", "Peace and Conflict Studies"),
                Subject("PAS", "Personnel & Administration Studies"),
                Subject("PD", "Professional Development"),
                Subject("PDARCH", "Professional Development for Architecture Students"),
                Subject("PDENG", "Professional Development for Engineering Students"),
                Subject("PDPHRM", "Professional Development for Pharmacy Students"),
                Subject("PED", "Physical Education (WLU)"),
                Subject("PERST", "Personnel Studies"),
                Subject("PHARM", "Pharmacy"),
                Subject("PHIL", "Philosophy"),
                Subject("PHS", "Public Health Sciences"),
                Subject("PHYS", "Physics"),
                Subject("PLAN", "Planning"),
                Subject("PMATH", "Pure Mathematics"),
                Subject("POLSH", "Polish"),
                Subject("PORT", "Portuguese"),
                Subject("PS", "Public Serivce"),
                Subject("PSCI", "Political Science"),
                Subject("PSYCH", "Psychology"),
                Subject("QIC", "Quantum Information and Computation"),
                Subject("REC", "Recreation and Leisure Studies"),
                Subject("REES", "Russian and Eastern European Studies"),
                Subject("RELC", "Religion & Culture (WLU)"),
                Subject("RS", "Religious Studies"),
                Subject("RSCH", "Research"),
                Subject("RUSS", "Russian"),
                Subject("SCBUS", "Science and Business"),
                Subject("SCI", "Science"),
                Subject("SDS", "Social Development Studies"),
                Subject("SE", "Software Engineering"),
                Subject("SEQ", "Co-op Sequence"),
                Subject("SI", "Studies in Islam"),
                Subject("SIPAR", "Studies in Personality & Religion"),
                Subject("SMF", "Sexuality, Marriage and the Family"),
                Subject("SOC", "Sociology"),
                Subject("SOCIN", "Social Innovation"),
                Subject("SOCWK", "Social Work (Social Development Studies)"),
                Subject("SOCWL", "Social Welfare (WLU)"),
                Subject("SPAN", "Spanish"),
                Subject("SPCOM", "Speech Communication"),
                Subject("SPD", "Spirituality and Personal Development"),
                Subject("STAT", "Statistics"),
                Subject("STV", "Society, Technology and Values"),
                Subject("SUSM", "Sustainability Management"),
                Subject("SWK", "Social Work"),
                Subject("SWREN", "Social Work (Bachelor of Social Work)"),
                Subject("SYDE", "Systems Design Engineering"),
                Subject("TAX", "Taxation"),
                Subject("THTRE", "Theatre (WLU)"),
                Subject("TN", "Theoretical Neuroscience"),
                Subject("TOUR", "Tourism"),
                Subject("TPM", "Technical Presentation Milestone"),
                Subject("TPPE", "Technical Presentation Proficiency Requirement"),
                Subject("TS", "Theological Studies"),
                Subject("UKRAN", "Ukrainian"),
                Subject("UN", "Nuclear Engineering"),
                Subject("UNIV", "University"),
                Subject("URBAN", "Urban Studies (WLU)"),
                Subject("UU", "University Interdisciplinary Studies (WLU)"),
                Subject("VCULT", "Visual Culture"),
                Subject("WATER", "Water"),
                Subject("WHMIS", "Workplace Hazardous Materials Information Systems"),
                Subject("WKRPT", "Work-term Report"),
                Subject("WS", "Women's Studies"),
                Subject("ZOOL", "Zoology (WLU)")
        )
    }
}
